//products
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const GET_PRODUCTS_BY_CATEGORY = "GET_PRODUCTS_BY_CATEGORY";
export const GET_PRODUCTS_BY_NAME = "GET_PRODUCTS_BY_NAME";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const SORT_BY_SCORE = "SORT_BY_SCORE";
export const SORT_BY_TIME_PREPARATION = "SORT_BY_TIME_PREPARATION";
export const CLEAR_PRODUCTS = "CLEAR_PRODUCTS";
export const FILTER_BY_DIET = "FILTER_BY_DIET";
export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const SORT_PRODUCTS_BY_PRICE = "SORT_PRODUCTS_BY_PRICE";
export const DELETE_PRODUCT_BY_ID = "DELETE_PRODUCT_BY_ID";
//profile
export const GET_PROFILE_BY_ID = "GET_PROFILE_BY_ID";
export const CREATE_PROFILE = "CREATE_PROFILE";

//cart
export const ADD_PRODUCT_CART = "ADD_PRODUCT_CART";
export const CLEAR_CART = "CLEAR_CART";

//Users
export const SAVESITE = "SAVESITE";
//Reservations

//orders
export const CREATE_ORDER = "CREATE_ORDER";
export const SAVE_ORDER = "SAVE_ORDER";
export const GET_ORDER = "GET_ORDER";
export const GET_ORDER_BY_ID = "GET_ORDER_BY_ID";
export const GET_ALL_ORDERS = "GET_ALL_ORDERS";
//check
export const CREATE_CHECK = "CREATE_CHECK";
export const SAVE_CHECK = "SAVE_CHECK";
export const GET_ALL_CHECK = "GET_ALL_CHECK";
export const GET_CHECK = "GET_CHECK";
//pago
export const GET_INFO_PAYMENT = "GET_INFO_PAYMENT";
export const GET_ORDERS_ID_PROFILE = "GET_ORDERS_ID_PROFILE";

//reservas
export const GET_RESERVAS_ACT_BY_ID_PROFILE = "GET_RESERVAS_ACT_BY_ID_PROFILE";
export const DELETE_RESERVATION = "DELETE_RESERVATION";
export const CREATE_RESERVATION = "CREATE_RESERVATION";

//review
export const CREATE_REVIEW = "CREATE_REVIEW";
export const GET_REVIEW_BY_ID_PROFILE = "GET_REVIEW_BY_ID_PROFILE";
export const GET_REVIEW_BY_ID_REVIEW = "GET_REVIEW_BY_ID_REVIEW";

//site
export const GET_SITE_ACTIVAS = "GET_SITE_ACTIVAS";
