export * from "./Landing";
export * from "./Login";
export * from "./Home";
export * from "./Cards";
export * from "./Cart";
export * from "./Details";
export * from "./NavBar";
export * from "./Pagination";
export * from "./Card";
export * from "./SearchBar";
export * from "./ResultSearch";
export * from "./CreateProduct";
export * from "./CreateProfile";
export * from "./Profile";
export * from "./OrderConfirmation";
export * from "./PayMercadoPago"
export * from "./QR_scanner"
